import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  bigint,
  numeric,
  boolean,
  timestamp,
  jsonb,
  index,
  unique,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { oracleConnections } from './connections';

export const sqlStatistics = pgTable('sql_statistics', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  sqlId: varchar('sql_id', { length: 13 }).notNull(),
  planHashValue: bigint('plan_hash_value', { mode: 'number' }),
  module: varchar('module', { length: 100 }),
  schemaName: varchar('schema_name', { length: 100 }),
  sqlText: text('sql_text').notNull(),
  sqlFulltext: text('sql_fulltext'),
  elapsedTimeMs: bigint('elapsed_time_ms', { mode: 'number' }).default(0),
  cpuTimeMs: bigint('cpu_time_ms', { mode: 'number' }).default(0),
  bufferGets: bigint('buffer_gets', { mode: 'number' }).default(0),
  diskReads: bigint('disk_reads', { mode: 'number' }).default(0),
  directWrites: bigint('direct_writes', { mode: 'number' }).default(0),
  executions: integer('executions').default(0),
  parseCalls: integer('parse_calls').default(0),
  rowsProcessed: bigint('rows_processed', { mode: 'number' }).default(0),
  avgElapsedTimeMs: numeric('avg_elapsed_time_ms', { precision: 12, scale: 2 }),
  avgCpuTimeMs: numeric('avg_cpu_time_ms', { precision: 12, scale: 2 }),
  getsPerExec: numeric('gets_per_exec', { precision: 12, scale: 2 }),
  rowsPerExec: numeric('rows_per_exec', { precision: 12, scale: 2 }),
  applicationWaitTimeMs: bigint('application_wait_time_ms', { mode: 'number' }).default(0),
  concurrencyWaitTimeMs: bigint('concurrency_wait_time_ms', { mode: 'number' }).default(0),
  clusterWaitTimeMs: bigint('cluster_wait_time_ms', { mode: 'number' }).default(0),
  userIoWaitTimeMs: bigint('user_io_wait_time_ms', { mode: 'number' }).default(0),
  firstLoadTime: timestamp('first_load_time', { withTimezone: true }),
  lastActiveTime: timestamp('last_active_time', { withTimezone: true }),
  lastLoadTime: timestamp('last_load_time', { withTimezone: true }),
  collectedAt: timestamp('collected_at', { withTimezone: true }).defaultNow(),
  snapshotId: bigint('snapshot_id', { mode: 'number' }),
  status: varchar('status', { length: 20 }).default('NORMAL'),
  priority: varchar('priority', { length: 20 }).default('MEDIUM'),
  metadata: jsonb('metadata').default({}),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  unique('uq_sql_statistics_conn_sql').on(table.oracleConnectionId, table.sqlId),
  index('idx_sql_statistics_oracle_conn').on(table.oracleConnectionId),
  index('idx_sql_statistics_sql_id').on(table.oracleConnectionId, table.sqlId),
  index('idx_sql_statistics_collected').on(table.collectedAt),
  index('idx_sql_statistics_status').on(table.status),
  index('idx_sql_statistics_priority').on(table.priority),
  index('idx_sql_statistics_elapsed').on(table.elapsedTimeMs),
  index('idx_sql_statistics_buffer').on(table.bufferGets),
  index('idx_sql_statistics_cpu').on(table.cpuTimeMs),
  index('idx_sql_statistics_connection_collected').on(table.oracleConnectionId, table.collectedAt),
]);

export const sqlExecutionHistory = pgTable('sql_execution_history', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  sqlStatisticsId: uuid('sql_statistics_id').references(() => sqlStatistics.id, { onDelete: 'cascade' }),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  sqlId: varchar('sql_id', { length: 13 }).notNull(),
  executionTime: timestamp('execution_time', { withTimezone: true }).notNull(),
  elapsedTimeMs: integer('elapsed_time_ms'),
  cpuTimeMs: integer('cpu_time_ms'),
  bufferGets: integer('buffer_gets'),
  diskReads: integer('disk_reads'),
  rowsProcessed: integer('rows_processed'),
  sid: integer('sid'),
  serialNumber: integer('serial_number'),
  username: varchar('username', { length: 100 }),
  program: varchar('program', { length: 100 }),
  planHashValue: bigint('plan_hash_value', { mode: 'number' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_sql_execution_history_sql_stats').on(table.sqlStatisticsId),
  index('idx_sql_execution_history_sql_id').on(table.oracleConnectionId, table.sqlId),
  index('idx_sql_execution_history_time').on(table.executionTime),
]);

export const waitEvents = pgTable('wait_events', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  eventName: varchar('event_name', { length: 100 }).notNull(),
  waitClass: varchar('wait_class', { length: 50 }),
  totalWaits: bigint('total_waits', { mode: 'number' }).default(0),
  totalTimeouts: bigint('total_timeouts', { mode: 'number' }).default(0),
  timeWaitedMs: bigint('time_waited_ms', { mode: 'number' }).default(0),
  averageWaitMs: numeric('average_wait_ms', { precision: 12, scale: 2 }),
  pctDbTime: numeric('pct_db_time', { precision: 5, scale: 2 }),
  collectedAt: timestamp('collected_at', { withTimezone: true }).defaultNow(),
  snapshotId: bigint('snapshot_id', { mode: 'number' }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_wait_events_oracle_conn').on(table.oracleConnectionId),
  index('idx_wait_events_collected').on(table.collectedAt),
  index('idx_wait_events_time_waited').on(table.timeWaitedMs),
]);

export const sessionMonitoring = pgTable('session_monitoring', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  sid: integer('sid').notNull(),
  serialNumber: integer('serial_number').notNull(),
  username: varchar('username', { length: 100 }),
  osuser: varchar('osuser', { length: 100 }),
  machine: varchar('machine', { length: 100 }),
  program: varchar('program', { length: 100 }),
  module: varchar('module', { length: 100 }),
  status: varchar('status', { length: 20 }),
  state: varchar('state', { length: 20 }),
  sqlId: varchar('sql_id', { length: 13 }),
  sqlText: text('sql_text'),
  event: varchar('event', { length: 100 }),
  waitClass: varchar('wait_class', { length: 50 }),
  waitTimeMs: integer('wait_time_ms'),
  logicalReads: bigint('logical_reads', { mode: 'number' }),
  physicalReads: bigint('physical_reads', { mode: 'number' }),
  cpuTimeMs: bigint('cpu_time_ms', { mode: 'number' }),
  logonTime: timestamp('logon_time', { withTimezone: true }),
  lastCallEt: integer('last_call_et'),
  blockingSession: integer('blocking_session'),
  blockingSessionStatus: varchar('blocking_session_status', { length: 20 }),
  collectedAt: timestamp('collected_at', { withTimezone: true }).defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_session_monitoring_oracle_conn').on(table.oracleConnectionId),
  index('idx_session_monitoring_sid').on(table.sid, table.serialNumber),
  index('idx_session_monitoring_sql_id').on(table.sqlId),
  index('idx_session_monitoring_collected').on(table.collectedAt),
]);

export const executionPlans = pgTable('execution_plans', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  sqlId: varchar('sql_id', { length: 13 }).notNull(),
  planHashValue: bigint('plan_hash_value', { mode: 'number' }).notNull(),
  planTable: jsonb('plan_table').notNull(),
  planText: text('plan_text'),
  optimizer: varchar('optimizer', { length: 50 }),
  cost: numeric('cost'),
  cardinality: bigint('cardinality', { mode: 'number' }),
  bytes: bigint('bytes', { mode: 'number' }),
  timestamp: timestamp('timestamp', { withTimezone: true }),
  firstLoadTime: timestamp('first_load_time', { withTimezone: true }),
  executions: integer('executions').default(0),
  avgElapsedTimeMs: numeric('avg_elapsed_time_ms', { precision: 12, scale: 2 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  unique('uq_execution_plans').on(table.oracleConnectionId, table.sqlId, table.planHashValue),
  index('idx_execution_plans_sql_id').on(table.oracleConnectionId, table.sqlId),
  index('idx_execution_plans_hash').on(table.planHashValue),
]);

export const sqlBindVariables = pgTable('sql_bind_variables', {
  id: uuid('id').primaryKey().default(sql`gen_random_uuid()`),
  oracleConnectionId: uuid('oracle_connection_id').notNull().references(() => oracleConnections.id, { onDelete: 'cascade' }),
  sqlId: varchar('sql_id', { length: 13 }).notNull(),
  position: integer('position').notNull(),
  name: varchar('name', { length: 100 }),
  datatype: varchar('datatype', { length: 50 }),
  valueString: text('value_string'),
  capturedAt: timestamp('captured_at', { withTimezone: true }).defaultNow(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow(),
}, (table) => [
  index('idx_sql_bind_variables_sql_id').on(table.oracleConnectionId, table.sqlId),
]);
